---
title: "Eissner_assign2"
author: "Jordan Eissner"
date: "March 14, 2018"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### Abstract





### Introduction



### Methods

```{r data, echo=FALSE}

DataMatrix <- function(data,na_thresh){
# make list of all names, lats, and lons
n <- distinct(tempdat, tempdat$name, tempdat$lon, tempdat$lat)
namelist <- n$`tempdat$name`
latlist <- n$`tempdat$lat`
lonlist <- n$`tempdat$lon`
yearlist <- unique(tempdat$year)
colnames(n) <- c('name', 'lat', 'lon')

# put data into a matrix with each location as a row and each year as a column
m <- matrix(data=data$data, nrow = length(namelist), ncol = length(yearlist), byrow=TRUE)

rownames(m) <- namelist
colnames(m) <- yearlist

r <- cbind(n,m)

# delete rows with more than threshold NA values
delete.na <- function(DF, a=0) {
  DF[rowSums(is.na(DF)) <= a,]
}
new_dat <- delete.na(r, na_thresh)
dat_only <- delete.na(m, na_thresh)
new_namelist <- new_dat$name
new_latlist <- new_dat$lat
new_lonlist <- new_dat$lon

return(list(dat_only=dat_only, latlist=new_latlist, lonlist=new_lonlist))
}
```


```{r trend, echo=FALSE}
Trend <- function(data) {
  yearlist <- colnames(data)
  namelist <- rownames(data)
  
  tm <- t(data)
  trend <- c()
  for(i in 1:length(namelist)){
    lm <- lm(yearlist ~ tm[,i])
    coeff <- lm$coefficients[2]
    trend <- c(trend,coeff)
  }
  return(trend)
}

```


```{r maps, echo=FALSE}
Map <- function(trend, lonlist, latlist){
  rbPal <- colorRampPalette(c('red','yellow','blue'))
  trend$Col <- rbPal(10)[as.numeric(cut(trend,breaks=10))]
  
  map("usa", fill=FALSE, plot=TRUE)
  points(lonlist, latlist, col = trend$Col, pch =19, cex = .6)
  #legend("bottomleft", legend=c("Pos","Neg"), col=trend$Col, fill=trend$Col)
}
 
```

```{r usefuncs, echo=FALSE}
library(maps)
library(graphics)
library(mapproj)
library(dplyr)

tempdat <- readRDS("USAAnnualTemp1950_2008.rds")
precdat <- readRDS("USAAnnualPcpn1950_2008.rds")

na_thresh <- 18 # remove station data if it has more than a threshold of NA values

new_data <- DataMatrix(tempdat,na_thresh)$dat_only
latlist <- DataMatrix(tempdat,na_thresh)$latlist
lonlist <- DataMatrix(tempdat,na_thresh)$lonlist

trend_data <- Trend(new_data)

Map(trend_data, latlist, lonlist)

# datasets <- c(tempdat, precdat)
# for (i in 1:length(datasets)) {
#   new_data <- DataMatrix(datasets[i], na_thresh)
#   trend_data <- Trend(new_data)
#   Map(trend_data)
# }

```


### Results



### Discussion



### References 



